Repository Go-Ride-Share/logic-layer, pull requests merged in 2024-11, with the labels that each got.

#51 Bug fix - Get all posts
  AccountManager.Tests/GetAllPostsTests.cs
  AccountManager/GetAllPosts.cs
Labels: bug

#52 Bug fix for no posts
  Logic.Tests/Posts/GetPostsTests.cs
  Logic/src/Posts/GetPosts.cs
Labels: bug

#53 Added a workflow file to auto-run regression tests
  .github/workflows/tests.yml
Labels: enhancement

#54 Added Continuous Deployment
  .github/workflows/docker-publish.yml
Labels: enhancement

#58 search for posts and refactoring
  AccountManager.Tests/GetAllPostsTests.cs
  AccountManager/CreateUser.cs
  AccountManager/FindPost.cs
  AccountManager/GetAllPosts.cs
  AccountManager/GetPost.cs
  AccountManager/HttpRequestHandler.cs
  AccountManager/IHttpRequestHandler.cs
  AccountManager/RequestObjects.cs
  AccountManager/VerifyLoginCredentials.cs
  Logic.Tests/Posts/GetPostsTests.cs
  Logic.Tests/Posts/SavePostTests.cs
  Logic.Tests/Users/EditUserTests.cs
  Logic/src/Messages/CreateConversation.cs
  Logic/src/Messages/GetAllConverstations.cs
  Logic/src/Messages/PollConversation.cs
  Logic/src/Messages/PostMessage.cs
  Logic/src/Posts/GetPosts.cs
  Logic/src/Posts/SavePost.cs
  Logic/src/Shared/HttpRequestHandler.cs
  Logic/src/Shared/IHttpRequestHandler.cs
  Logic/src/Shared/RequestObjects.cs
  Logic/src/Users/EditUser.cs
  Logic/src/Users/GetUser.cs
Labels: Feature

#59 Fix CreateConversations
  AccountManager.Tests/GetAllPostsTests.cs
  AccountManager/RequestObjects.cs
  Logic.Tests/Posts/GetPostsTests.cs
  Logic.Tests/Posts/SavePostTests.cs
  Logic/src/Shared/RequestObjects.cs
Labels: bug

#61 Re-route getPost
  AccountManager/GetPost.cs
  Logic/src/Posts/SavePost.cs
Labels: bug

#62 Changed API endpoints
  AccountManager/CreateUser.cs
  AccountManager/FindPost.cs
  AccountManager/GetAllPosts.cs
  AccountManager/GetPost.cs
  AccountManager/GetPosts.cs
  AccountManager/LoginUser.cs
  Logic.Tests/Messages/GetConversationsTests.cs
  Logic.Tests/Messages/GetMessagesTests.cs
  Logic.Tests/Posts/GetPostsTests.cs
  Logic.Tests/Users/GetUserTests.cs
  Logic/src/Messages/CreateConversation.cs
  Logic/src/Messages/GetConversations.cs
  Logic/src/Messages/GetMessages.cs
  Logic/src/Messages/PostMessage.cs
  Logic/src/Posts/GetPosts.cs
  Logic/src/Posts/SavePost.cs
  Logic/src/Users/EditUser.cs
  Logic/src/Users/GetUser.cs
Labels: enhancement

#63 Google login
  AccountManager/AccountManager.csproj
  AccountManager/CreateUser.cs
  AccountManager/GoogleLogin.cs
  AccountManager/PasswordLogin.cs
  AccountManager/RequestObjects.cs
  Logic.Tests/Posts/GetPostsTests.cs
  Logic/src/Posts/GetPosts.cs
  Logic/src/Users/GetUser.cs
Labels: Feature

#64 Deploying to Production - for DEMO
  .github/workflows/main_grs-accountmanager.yml
  AccountManager.Tests/GetAllPostsTests.cs
  AccountManager/AccountManager.csproj
  AccountManager/CreateUser.cs
  AccountManager/FindPost.cs
  AccountManager/GetAllPosts.cs
  AccountManager/GetPosts.cs
  AccountManager/GoogleLogin.cs
  AccountManager/HttpRequestHandler.cs
  AccountManager/IHttpRequestHandler.cs
  AccountManager/PasswordLogin.cs
  AccountManager/RequestObjects.cs
  Logic.Tests/Messages/GetConversationsTests.cs
  Logic.Tests/Messages/GetMessagesTests.cs
  Logic.Tests/Posts/GetPostsTests.cs
  Logic.Tests/Posts/SavePostTests.cs
  Logic.Tests/Users/EditUserTests.cs
  Logic.Tests/Users/GetUserTests.cs
  Logic/src/Messages/CreateConversation.cs
  Logic/src/Messages/GetConversations.cs
  Logic/src/Messages/GetMessages.cs
  Logic/src/Messages/PostMessage.cs
  Logic/src/Posts/GetPosts.cs
  Logic/src/Posts/SavePost.cs
  Logic/src/Shared/HttpRequestHandler.cs
  Logic/src/Shared/IHttpRequestHandler.cs
  Logic/src/Shared/RequestObjects.cs
  Logic/src/Users/EditUser.cs
  Logic/src/Users/GetUser.cs
Labels: Feature
