Repository Go-Ride-Share/logic-layer, pull requests merged in 2024-12, with the labels that each got.

#70 Verify UserId and Tokens Before Accessing Logic
  AccountManager/AccountManager.csproj
  AccountManager/CreateUser.cs
  AccountManager/GoogleLogin.cs
  AccountManager/PasswordLogin.cs
  AccountManager/SecurityGuard.cs
  AccountManager/sample.local.settings.json
  Logic.Tests/Messages/CreateConversationTests.cs
  Logic.Tests/Messages/GetConversationsTests.cs
  Logic.Tests/Messages/GetMessagesTests.cs
  Logic.Tests/Messages/PostMessageTests.cs
  Logic.Tests/Posts/GetPostsTests.cs
  Logic.Tests/Posts/SavePostTests.cs
  Logic.Tests/Users/EditUserTests.cs
  Logic.Tests/Users/GetUserTests.cs
  Logic/Logic.csproj
  Logic/sample.local.settings.json
  Logic/src/Messages/CreateConversation.cs
  Logic/src/Messages/GetConversations.cs
  Logic/src/Messages/GetMessages.cs
  Logic/src/Messages/PostMessage.cs
  Logic/src/Posts/GetPosts.cs
  Logic/src/Posts/SavePost.cs
  Logic/src/Shared/AzureTableService.cs
  Logic/src/Shared/HttpRequestHandler.cs
  Logic/src/Shared/IAzureTableService.cs
  Logic/src/Shared/IHttpRequestHandler.cs
  Logic/src/Shared/Program.cs
  Logic/src/Shared/Utilities.cs
  Logic/src/Users/EditUser.cs
  Logic/src/Users/GetUser.cs
Labels: Feature

#71 Fix security issue
  AccountManager/AccountManager.csproj
  Logic/Logic.csproj
  Logic/src/Users/GetUser.cs
Labels: enhancement

#72 Documentation/update readme and api docs
  AccountManager/Endpoints.yaml
  README.md
Labels: documentation
