Repository Go-Ride-Share/logic-layer, pull requests merged in 2024-10, with the labels that each got.

#25 Update readme to list all the live endpoints.
  README.md
Labels: documentation

#47 Remove Dummy endpoint responses
  AccountManager/GetAllPosts.cs
  Logic/src/Messages/CreateConversation.cs
  Logic/src/Messages/GetAllConverstations.cs
  Logic/src/Messages/PollConversation.cs
  Logic/src/Messages/PostMessage.cs
  Logic/src/Shared/RequestObjects.cs
Labels: Feature

#46 Refactor for better project structure
  .gitignore
  AccountManager.Tests/AccountManager.Tests.csproj
  AccountManager.Tests/GetAllPostsTests.cs
  AccountManager/AccountManager.csproj
  AccountManager/AccountManager.sln
  Logic.Tests/Logic.Tests.csproj
  Logic.Tests/Messages/CreateConversationTests.cs
  Logic.Tests/Messages/GetAllConversationsTests.cs
  Logic.Tests/Messages/PollConversationTests.cs
  Logic.Tests/Messages/PostMessageTests.cs
  Logic.Tests/Posts/GetPostsTests.cs
  Logic.Tests/Posts/SavePostTests.cs
  Logic.Tests/Users/EditUserTests.cs
  Logic.Tests/Users/GetUserTests.cs
  Logic/.gitignore
  Logic/Logic.csproj
  Logic/Logic.sln
  Logic/src/Messages/CreateConversation.cs
  Logic/src/Messages/GetAllConverstations.cs
  Logic/src/Messages/PollConversation.cs
  Logic/src/Messages/PostMessage.cs
  Logic/src/Posts/GetAllPosts.cs
  Logic/src/Users/EditUser.cs
  LogicLayer.sln
Labels: enhancement

#48 Bug fix for poll conversation
  Logic/src/Messages/PollConversation.cs
Labels: bug

#50 Added more tests
  Logic.Tests/Messages/CreateConversationTests.cs
  Logic.Tests/Messages/GetAllConversationsTests.cs
  Logic.Tests/Messages/PollConversationTests.cs
  Logic.Tests/Messages/PostMessageTests.cs
Labels: enhancement

#49 Add docker files
  AccountManager/.dockerignore
  AccountManager/Dockerfile
  Logic/.dockerignore
  Logic/Dockerfile
Labels: Feature
